### ISSUE TITLE
can't paste schematics with a low delay

### ISSUE THREAD

**Issue by iTrooz** [Efnilite/Skematic#10]
when we do a loop , with a delay of... 1-20 ticks of delay between pasting , we get this error after a moment 

```
[17:07:37] [Server thread/WARN]: [Skript] Task #4206 for Skript v2.2-dev32c generated an exception
java.lang.IllegalAccessError: com/sk89q/worldedit/bukkit/BukkitEntity
	at com.sk89q.worldedit.bukkit.BukkitWorld.createEntity(BukkitWorld.java:150) ~[?:?]
	at com.boydti.fawe.wrappers.WorldWrapper.createEntity(WorldWrapper.java:316) ~[?:?]
	at com.boydti.fawe.object.schematic.Schematic.paste(Schematic.java:273) ~[?:?]
	at com.efnilite.skematic.objects.Schematic.paste(Schematic.java:34) ~[?:?]
	at com.efnilite.skematic.elements.effects.EffSchematicPaste.execute(EffSchematicPaste.java:106) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.effects.Delay$1.run(Delay.java:101) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[spigot-1.12.2-2.jar:git-Paper-1552]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[spigot-1.12.2-2.jar:git-Paper-1552]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[spigot-1.12.2-2.jar:git-Paper-1552]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[spigot-1.12.2-2.jar:git-Paper-1552]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[spigot-1.12.2-2.jar:git-Paper-1552]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[spigot-1.12.2-2.jar:git-Paper-1552]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by Efnilite** [comment]
This is probably fixed in 2.2 since all classes have been updated to match newer versions.
If this issue still persists, please say so
