### ISSUE TITLE
Issue with loading and pasting a schematic (EDITED: error while enabling skematic)

### ISSUE THREAD

**Issue by klmzHC** [Efnilite/Skematic#11]
Struggling to get this code to work:

on game start:
	load schematic "plugins/Skript/schematics/FBArena.schematic" as "arena"

on game enabled:
	wait 1 minute
	if custom world name is "Citta'":
		paste the schematic "arena" at location (-1, 48, 0)

Error:
[02:51:34 ERROR]: Can't understand this condition/effect: load schematic "plugins/Skript/schematics/FBArena.schematic" as "arena" (finalbattle.sk, line 2: load schematic "plugins/Skript/schematics/FBArena.schematic" as "arena"')
[02:51:34 ERROR]: Can't understand this condition/effect: paste the schematic "arena" at location (-1, 48, 0) (finalbattle.sk, line 7: paste the schematic "arena" at location (-1, 48, 0)')
[02:51:34 INFO]: [Skript] Encountered 2 errors while reloading finalbattle.sk!

I also tried to store the schematic in a variable, but with no success.
Please help me!

**Comment by Efnilite** [comment]
Please use the issue template next time when creating an issue. I don't know your version, meaning I can't really help with the load error. This was added in 2.1, and if you're using a version before that, please update to 2.2b if you're using 1.13, else, use 2.2.

The 2nd error is a syntax problem with the `%location%` part, since you should be using the `location()` function, but this is more like a vector. What you probably meant was ` location(-1, 48, 0)`

**Comment by klmzHC** [comment]
Thanks for your reply, but I think I found the error that I didn't notice since I was working on this at 3 am lol: Skematic was not enabled at all because I didn't install FAWE. So I proceeded to install it and the server returned me this error:

[18:22:10 ERROR]: Error occurred while enabling Skematic v2.2b (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
        at com.efnilite.skematic.elements.expressions.ExprCuboidRegionPoints.<clinit>(ExprCuboidRegionPoints.java:27) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
        at com.efnilite.skematic.Skematic.onEnable(Skematic.java:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.math.BlockVector3
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 16 more

Furthermore it essentially broke Skript and every other Skript-related plugin.
I'm sorry that in my previous message I didn't specify the versions of the stuff I'm working with; so here they are:
Spigot - 1.12.2-R0.1-SNAPSHOT
Skript - 2.2-dev36
Skematic - 2.2b
FAWE - FastAsyncWorldEdit-bukkit-19.05.02-d89cb44-1274-22.2.0

If there is anything else I must specify to let you help me with this problem, just tell me!
Thank you.

**Comment by Efnilite** [comment]
2.2b is currently only for 1.13, so try using 2.2

**Comment by klmzHC** [comment]
I'm so stupid… How could I not see it… Thank you!
