### ISSUE TITLE
paste issue

### ISSUE THREAD

**Issue by koalas11** [Efnilite/Skematic#2]
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:03:04] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:03:04] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:03:04] [Server thread/ERROR]: #!#! Here is full list of them:
[22:03:04] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) Skematic Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SharpSK 
[22:03:04] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:03:04] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:03:04] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:03:04] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:03:04] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:03:04] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! Stack trace:
[22:03:04] [Server thread/ERROR]: #!#! java.lang.ClassCastException: ch.njol.skript.util.Direction$1 cannot be cast to org.bukkit.Location
[22:03:04] [Server thread/ERROR]: #!#!     at com.efnilite.skematic.elements.effects.EffPasteSchematic.execute(EffPasteSchematic.java:38)
[22:03:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[22:03:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:03:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:03:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[22:03:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[22:03:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[22:03:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:03:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[22:03:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[22:03:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:150)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:953)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:03:04] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:03:04] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[22:03:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[22:03:04] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! Version Information:
[22:03:04] [Server thread/ERROR]: #!#!   Skript: 2.3-beta6 (latest)
[22:03:04] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[22:03:04] [Server thread/ERROR]: #!#!     Timestamp: 2018-12-23
[22:03:04] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[22:03:04] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[22:03:04] [Server thread/ERROR]: #!#!   Java: 1.8.0_191 (Java HotSpot(TM) 64-Bit Server VM 25.191-b12)
[22:03:04] [Server thread/ERROR]: #!#!   OS: Windows Server 2012 R2 amd64 6.3
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! Server platform: Spigot
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! Current node: null
[22:03:04] [Server thread/ERROR]: #!#! Current item: paste schematic "plugins/WorldEdit/schematics/casa1.schematic" at at
[22:03:04] [Server thread/ERROR]: #!#! Current trigger: place (break/place/burn/fade/form of <none>) (test.sk, line 53)
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! Thread: Server thread
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! Language: english
[22:03:04] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:03:04] [Server thread/ERROR]: #!#! 
[22:03:04] [Server thread/ERROR]: #!#! End of Error.
[22:03:04] [Server thread/ERROR]: #!#! 

Got this error after doing this event
on place:
    if event-block is ender chest:
        if block below event-location is grass:
            loop all blocks in radius 14 around event-block:
                if loop-block is Oak Plank:
                    add 1 to {_saf}
            if {_saf} is set:
                cancel event
                send "Sei troppo vicino ad un'altra casa"
            else:
                cancel event
                remove 1 ender chest from player
                paste skematic "plugins/WorldEdit/schematics/casa1.schematic" at event-location

it broke with new update

**Comment by Efnilite** [comment]
Fixing this tomorrow in next release

**Comment by Efnilite** [comment]
Fixed in https://github.com/Efnilite/Skematic/releases/tag/2.1
