### ISSUE TITLE
Skematic won't work

### ISSUE THREAD

**Issue by KittensAreHot** [Efnilite/Skematic#4]
when i am trying to use Skematic skript crashes

**Comment by Efnilite** [comment]
![cover4](https://user-images.githubusercontent.com/35348263/84580294-e59afb00-add5-11ea-927c-4aec39bd2059.jpg) Skematic version? Skript version? Server version? Whats the error? What do you mean with 'skript crashes'?

**Comment by KittensAreHot** [comment]
I was rushing to post this issue cause i had to go for a while....

**Skematic version:** i tried all of them...

**Skript version:** 2.4.1

**Server version:**  1.12.2

**Whats the error:** 

`
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[03:02:09] [Server thread/ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[03:02:09] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[03:02:09] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[03:02:09] [Server thread/ERROR]: #!#! Following plugins are probably related to this error in some way:
[03:02:09] [Server thread/ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) 
[03:02:09] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[03:02:09] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[03:02:09] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[03:02:09] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[03:02:09] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! Stack trace:
[03:02:09] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[03:02:09] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[03:02:09] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[03:02:09] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[03:02:09] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[03:02:09] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[03:02:09] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:02:09] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[03:02:09] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[03:02:09] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[03:02:09] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[03:02:09] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[03:02:09] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[03:02:09] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[03:02:09] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[03:02:09] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[03:02:09] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! Version Information:
[03:02:09] [Server thread/ERROR]: #!#!   Skript: 2.4.1 (latest)
[03:02:09] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[03:02:09] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[03:02:09] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[03:02:09] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[03:02:09] [Server thread/ERROR]: #!#!   Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b03)
[03:02:09] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.15.0-91-generic
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! Server platform: Spigot
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! Current node: null
[03:02:09] [Server thread/ERROR]: #!#! Current item: null
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! Thread: Server thread
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! Language: english
[03:02:09] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[03:02:09] [Server thread/ERROR]: #!#! 
[03:02:09] [Server thread/ERROR]: #!#! End of Error.
[03:02:09] [Server thread/ERROR]: #!#! `

It says there that it thinks the problem is with TuSKe but the problem disappears just when I remove Skematic and if I remove TuSKe it stills give me the error just saying a different list of addons... 

here is the list of the addons I use if you need it to help

**Addons:**
  - skDragon
  -Skellett
  - skRayFall
  - TuSKe
  - skript-json
  - SkQuery
  - Ersatz

**Comment by KittensAreHot** [comment]
i can you please respond sorry if i am rushing you

**Comment by KittensAreHot** [comment]
amm...

**Comment by Efnilite** [comment]
TuSKe problem, as shown in the stack trace: `TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception`
