### ISSUE TITLE
Skematic not working with latest worldedit build

### ISSUE THREAD

**Issue by bloggy** [Efnilite/Skematic#7]
See error:

```
[14:42:26] [Server thread/INFO]: [Skematic] Enabling Skematic v2.1
[14:42:26] [Server thread/ERROR]: Error occurred while enabling Skematic v2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at com.efnilite.skematic.elements.expressions.ExprCuboidRegionPoints.<clinit>(ExprCuboidRegionPoints.java:27) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
	at com.efnilite.skematic.Skematic.onEnable(Skematic.java:28) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 16 more
[14:42:26] [Server thread/INFO]: [Skematic] Disabling Skematic v2.1
```

Version: skematic 2.1
worldedit: WorldEdit Build #4048 (Link: [http://builds.enginehub.org/job/worldedit/10982](http://builds.enginehub.org/job/worldedit/10982) )

**Comment by Efnilite** [comment]
Skematic only works with FAWE (https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/)
